stages:
  - unit test
  - package
  - test
  - production
  - post production

variables:
  APP_VERSION: $CI_PIPELINE_IID
  VARIABLES_FILE: ./variables.txt


.prepare ssh:
  before_script:
    - apk --no-cache add openssh-client curl
    - mkdir -p ~/.ssh
    - eval $(ssh-agent -s)
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
    - chmod 600 $SSH_PRIVATE_KEY
    - ssh-add $SSH_PRIVATE_KEY


.prepare app:
  before_script:
    - cp .env.example .env
    - sed -i "s/APP_KEY=.*/APP_KEY=$APP_KEY/" .env
    - sed -i "s/REDIS_HOST=.*/REDIS_HOST=$REDIS_HOST/" .env
    - sed -i "s/BITPIN_VERSION/$APP_VERSION/" resources/views/welcome.blade.php
    - rm .env  # intentional mistake

unit test:
  image: php:8.2-alpine
  stage: unit test
  extends:
    - .prepare app
  before_script:
    - apk --no-cache add autoconf build-base curl
    - curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
    - pecl install redis && docker-php-ext-enable redis
    - composer install
  script:
    - php artisan test

build docker image:
  stage: package
  image: docker:27.0.3
  services:
    - docker:27.0.3-dind
  extends:
    - .prepare app
  script:
    - echo $CI_REGISTRY_PASSWORD | docker login -u $CI_REGISTRY_USER $CI_REGISTRY --password-stdin
    - docker build -t $CI_REGISTRY_IMAGE -t $CI_REGISTRY_IMAGE:$APP_VERSION -t $DOCKER_REGISTRY_IMAGE -t $DOCKER_REGISTRY_IMAGE:$APP_VERSION .
    - 'if [ ! -z $CI_COMMIT_TAG ]; then docker tag $CI_REGISTRY_IMAGE:latest $CI_REGISTRY_IMAGE:prod; fi'
    - docker push --all-tags $CI_REGISTRY_IMAGE
    - echo $DOCKER_REGISTRY_PASSWORD | docker login -u $DOCKER_REGISTRY_USERNAME --password-stdin
    - docker push --all-tags $DOCKER_REGISTRY_IMAGE

test docker image:
  image: curlimages/curl
  stage: test
  allow_failure: true
  services:
    - name: $CI_REGISTRY_IMAGE:$APP_VERSION
      alias: website
  script:
    - curl http://website:8000 | grep -q Version | grep -q $APP_VERSION

deploy to production:
  stage: production
  image: alpine
#  when: manual
#  rules:
#    - if: '$CI_COMMIT_TAG'
  variables:
    APP_NAME: infra-task-app-1
  extends:
    - .prepare ssh
  script:
    - ssh $PRODUCTION_SERVER "echo $DOCKER_REGISTRY_PASSWORD | docker login -u $DOCKER_REGISTRY_USERNAME --password-stdin"
    - |
      FORMER_IMAGE_NAME=$(docker inspect --format='{{.Config.Image}}' "$APP_NAME" 2>/dev/null || echo Not Found!)
      if [ "$FORMER_IMAGE_NAME" != "Not Found!" ]; then
        FORMER_IMAGE_VERSION=$(echo "$FORMER_IMAGE_NAME" | awk -F: '{print $2}')
        echo "Extracted version: $FORMER_IMAGE_VERSION"
      else
        FORMER_IMAGE_VERSION=0
        echo "Container not found!"
      fi
    - sed -i "s/latest/$APP_VERSION/" docker-compose.yml.example
    - scp docker-compose.yml.example $PRODUCTION_USER@$PRODUCTION_SERVER:/tmp/docker-compose.yml
    - ssh $PRODUCTION_USER@$PRODUCTION_SERVER "cd /tmp && docker compose pull && docker compose up -d"
    - echo "export FORMER_IMAGE_VERSION=$FORMER_IMAGE_VERSION" > $VARIABLES_FILE
  artifacts:
    paths:
      - $VARIABLES_FILE


test production server:
  image: alpine
  stage: post production
  extends:
    - .prepare ssh
  script:
    - source $VARIABLES_FILE
    - CONTENT=$(curl -s "http://$PRODUCTION_SERVER:8000")
    - |
      if echo "$CONTENT" | grep -q Version | grep -q $APP_VERSION; then
        echo "Success"
        exit 0
      else
        echo FORMER_IMAGE_VERSION: $FORMER_IMAGE_VERSION
        if [ $FORMER_IMAGE_VERSION -eq 0 ]; then
          echo "Failed and cannot rollback!"
          exit 1
        else
          sed -i "s/$APP_VERSION/$FORMER_IMAGE_VERSION/" docker-compose.yml.example
          scp docker-compose.yml.example $PRODUCTION_USER@$PRODUCTION_SERVER:/tmp/docker-compose.yml
          ssh $PRODUCTION_USER@$PRODUCTION_SERVER "cd /tmp && docker compose pull && docker compose up -d"
          sleep 10
          curl http://$PRODUCTION_SERVER:8000 | grep -q Version | grep -q $FORMER_IMAGE_VERSION
          if [[ $? -ne 0 ]]; then
            echo "Rollback failed!"
            exit 1
          else
            echo "Rollback was Successful"
            exit 0
          fi
        fi
      fi
