events {
    worker_connections 1024;  # Adjust as necessary for your needs
}
http {
    upstream app_servers {
        server app_blue:8000;  # Old version
        server app_green:8000;  # New version
    }

    server {
        listen 80;

        location / {
            proxy_pass http://app_servers;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }
}
