---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: infra-task
  name: infra-task
spec:
  ports:
    - name: http
      port: 8000
      protocol: TCP
  selector:
    app: infra-task
  type: ClusterIP
